[build]
target = "xtensa-esp8266-none-elf"
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "link-arg=-Wl,-Tlink.x"]

[target.xtensa-esp8266-none-elf]
runner = "espflash flash --monitor"

[unstable]
build-std = ["core"]
